spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: # h2 url ex_): jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: # h2 id
    password: # h2 password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

    open-in-view: false

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.kr.matitting
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: demo-ui.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

kakao:
  client-id: d5741d35440025fd9b0a7537f7a8aaf8
  client-secret: nPsWMJBVUzFqFncJGsLQwPB2HdG95e36
  redirect-uri: http://localhost:8080/auth/kakao/callback