spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: #jdbc:postgresql://localhost:5432/<DB명>
    username: #<PostgreSQL 계정명>
    password: #<비밀번호>
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace