spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

    open-in-view: false

  output:
    ansi:
      enabled: always

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  config:
    activate:
      on-profile: dev
  freemarker:
    cache: false
    enabled: true
    template-loader-path: classpath:/templates

  redis:
    host: localhost
    port: 6379

  datasource:
    url: # h2 url ex_): jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: # h2 id
    password: # h2 password

oauth:
  kakao:
    token_url: "https://kauth.kakao.com/oauth/token"
    user_url: "https://kapi.kakao.com/v2/user/me"
    grant_type: authorization_code
    client_id: 카카오 Client Code
    client_secret: 카카오 Client Secret Code
    redirect_uri: 카카오 Redirect URI

  naver:
    token_url: "https://nid.naver.com/oauth2.0/token"
    user_url: "https://openapi.naver.com/v1/nid/me"
    grant_type: authorization_code
    client_id: 네이버 Client Code
    client_secret: 네이버 Client Secret Code
    redirect_uri: 네이버 Redirect URI

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.kr.matitting
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: demo-ui.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

logging:
  level:
    root: info

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

  access:
    expiration: 1800000
    header: Authorization

  refresh:
    expiration: 259200000

    header: Authorization-Refresh

kakaoMap:
  key: REST API 키

cloud:
  aws:
    s3:
      url: <url>
      bucket: <버킷이름>
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: <발급받은 accessKey>
      secretKey: <발급받은 secretKey>
