spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  redis:
    host: localhost
    port: 6379

  datasource:
    url: # h2 url ex_): jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: # h2 id
    password: # h2 password

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 카카오 클라이언트 ID
            client-secret: 카카오 클라이언트 Secret
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email, profile_nickname, profile_image
            client-name: Kakao
          naver:
            client-id: 네이버 클라이언트 ID
            client-secret: 네이버 클라이언트 Secret
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

    open-in-view: false

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.kr.matitting
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: demo-ui.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

  access:
    expiration: 1800000
    header: Authorization

  refresh:
    expiration: 259200000

    header: Authorization-refresh